### ISSUE TITLE
What will the Names of our VM's be?

### ISSUE THREAD

**Issue by AlexMulkerrinQA** [AlexMulkerrinQA/ATMTN#2]

**Comment by AlexMulkerrinQA** [comment]
Choose your own VM's name
I'll be calling the puppet master swarmlord :D

**Comment by Dharam-G** [comment]
Mine will be called agent1

**Comment by tg1010** [comment]
mine will be called secretagent360noscope

**Comment by wjohnston4** [comment]
I'll be agent2.  keeps it easy to remember

**Comment by AJLProjects** [comment]
agent007

**Comment by AlexMulkerrinQA** [comment]
Awesome, now add them to the vagrant file!
